const mongoose =
require("mongoose");



// ======================
// INSTALLMENT SCHEMA
// ======================

const installmentSchema =
new mongoose.Schema({

  installmentName: {

    type: String,

    required: true
  },

  dueDate: {

    type: Date,

    required: true
  },

  amount: {

    type: Number,

    required: true,

    min: 0
  },

  status: {

    type: String,

    enum: [

      "PENDING",
      "PARTIAL",
      "PAID",
      "OVERDUE"
    ],

    default: "PENDING"
  },

  paidAmount: {

    type: Number,

    default: 0
  }

}, {

  _id: true
});



// ======================
// FEE ASSIGNMENT
// ======================

const feeAssignmentSchema =
new mongoose.Schema({

  feeStructureId: {

    type:
      mongoose.Schema.Types.ObjectId,

    ref: "FeeStructure",

    required: true
  },

 categoryId: {

  type:
    mongoose.Schema.Types.ObjectId,

  ref: "FeeCategory",

  required: false,

  default: null
},
  title: {

    type: String,

    required: true
  },

  code: {

    type: String,

    required: true
  },

  amount: {

    type: Number,

    required: true
  },

  recurringType: {

    type: String,

    enum: [

      "MONTHLY",
      "QUARTERLY",
      "YEARLY",
      "ONE_TIME"
    ],

    required: true
  },

  mandatory: {

    type: Boolean,

    default: true
  },

  assignedDate: {

    type: Date,

    default: Date.now
  },

  dueDate: {

    type: Date,

    required: true
  },

  allowInstallments: {

    type: Boolean,

    default: false
  },

  installments: [

    installmentSchema
  ],

  lateFineEnabled: {

    type: Boolean,

    default: true
  },

  lateFineAmount: {

    type: Number,

    default: 0
  },

  status: {

    type: String,

    enum: [

      "PENDING",
      "PARTIAL",
      "PAID",
      "WAIVED",
      "CANCELLED"
    ],

    default: "PENDING"
  },
  paidAmount: {

  type: Number,

  default: 0
},

pendingAmount: {

  type: Number,

  default: function () {

    return this.amount;
  }
},

discountAmount: {

  type: Number,

  default: 0
},

fineAmount: {

  type: Number,

  default: 0
},

paymentStatus: {

  type: String,

  enum: [

    "UNPAID",

    "PARTIAL",

    "PAID"
  ],

  default: "UNPAID"
},

  notes: {

    type: String,

    default: ""
  }

}, {

  _id: true
});



// ======================
// MAIN PROFILE
// ======================

const studentFeeProfileSchema =
new mongoose.Schema({

  schoolId: {

    type: String,

    required: true,

    index: true
  },

  academicYear: {

    type: String,

    required: true,

    index: true
  },

  studentId: {

    type:
      mongoose.Schema.Types.ObjectId,

    ref: "Student",

    required: true,

    index: true
  },

  className: {

    type: String,

    required: true,

    trim: true
  },

  section: {

    type: String,

    trim: true
  },

  rollNumber: {

    type: String,

    default: ""
  },

  feeAssignments: [

    feeAssignmentSchema
  ],

  totalAssignedAmount: {

    type: Number,

    default: 0
  },

  totalPaidAmount: {

    type: Number,

    default: 0
  },

  totalDiscountAmount: {

    type: Number,

    default: 0
  },

  totalFineAmount: {

    type: Number,

    default: 0
  },

  totalPendingAmount: {

    type: Number,

    default: 0
  },

  lastPaymentDate: Date,

  profileStatus: {

    type: String,

    enum: [

      "ACTIVE",
      "INACTIVE",
      "GRADUATED",
      "LEFT"
    ],

    default: "ACTIVE"
  },

  autoGenerated: {

    type: Boolean,

    default: true
  },

  remarks: {

    type: String,

    default: ""
  },

  createdBy: {

    type:
      mongoose.Schema.Types.ObjectId,

    ref: "User"
  },

  updatedBy: {

    type:
      mongoose.Schema.Types.ObjectId,

    ref: "User"
  },

  isDeleted: {

    type: Boolean,

    default: false
  }

}, {

  timestamps: true
});



// ======================
// INDEXES
// ======================

studentFeeProfileSchema.index({

  schoolId: 1,

  academicYear: 1,

  studentId: 1

}, {

  unique: true
});

studentFeeProfileSchema.index({

  schoolId: 1,

  className: 1
});

studentFeeProfileSchema.index({

  schoolId: 1,

  profileStatus: 1
});



// ======================
// PRE SAVE CALCULATIONS
// ======================

studentFeeProfileSchema.pre(
  "save",
  function() {

    const totalAssigned =
      this.feeAssignments.reduce(
        (sum, item) => {
          return sum + (item.amount || 0);
        },
        0
      );

    this.totalPaidAmount =
  this.feeAssignments.reduce(
    (sum, item) =>
      sum + (item.paidAmount || 0),
    0
  );

this.totalPendingAmount =
  this.feeAssignments.reduce(
    (sum, item) =>
      sum + (
        item.pendingAmount ??
        item.amount
      ),
    0
  );
  })
// ======================
// EXPORT
// ======================

module.exports =
mongoose.model(
  "StudentFeeProfile",
  studentFeeProfileSchema
);