const Student =
require(
  "../../../models/Student"
);
const FeeStructure =
require(
  "../models/FeeStructure"
);

const StudentFeeProfile =
require(
  "../models/StudentFeeProfile"
);



// ======================
// ASSIGN FEES TO STUDENT
// ======================
const assignFeesToStudent =
async ({

  schoolId,
  academicYear,
  student,
  createdBy

}) => {

  console.log(
    "ASSIGNING STUDENT =",
    student.name,
    student.currentClassName
  );

  try {    // ======================
    // FIND ACTIVE STRUCTURE
    // ======================

    const feeStructure =
      await FeeStructure.findOne({
        

        schoolId,

        academicYear,

        className:
          student.currentClassName,

        $or: [

          {

          section:
  student.currentSection || ""
          },

          {

            section:
              "ALL"
          }
        ],

        status: "ACTIVE",

        isDeleted: false
      });

      console.log(
  "FEE STRUCTURE FOUND =",
  feeStructure
);




    // ======================
    // NO STRUCTURE
    // ======================

    if (!feeStructure) {

      throw new Error(
        "No active fee structure found"
      );
    }



    // ======================
    // PREVENT DUPLICATE
    // ======================

    const existingProfile =
      await StudentFeeProfile.findOne({

        schoolId,

        academicYear,

        studentId:
          student._id,

        isDeleted: false
      });




    if (existingProfile) {

      return existingProfile;
    }



    // ======================
    // GENERATE ASSIGNMENTS
    // ======================

    const feeAssignments =
      feeStructure.feeItems.map(

        (item) => {

          // ======================
          // DUE DATE
          // ======================

          const dueDate =
            new Date();




          if (
            item.dueDay
          ) {

            dueDate.setDate(
              item.dueDay
            );
          }



          return {

            feeStructureId:
              feeStructure._id,



          categoryId:
  item.categoryId || null,



            title:
              item.title,



            code:
              item.code,



            amount:
              item.amount,



            recurringType:
              item.recurringType,



            mandatory:
              item.mandatory,



            dueDate,



            allowInstallments:
              item.installmentAllowed,



            lateFineEnabled:
              item.lateFineEnabled,



            lateFineAmount:
              item.lateFineAmount,



            // ======================
            // PAYMENT TRACKING
            // ======================

            paidAmount: 0,



            pendingAmount:
              item.amount,



            discountAmount: 0,



            fineAmount: 0,



            status:
              "PENDING",



            paymentStatus:
              "UNPAID"
          };
        }
      );



    // ======================
    // CREATE PROFILE
    // ======================

console.log("BEFORE CREATE");

const profile =
  await StudentFeeProfile.create({
    schoolId,
    academicYear,
    studentId: student._id,
    className: student.currentClassName,
    section: student.currentSection,
    rollNumber: student.rollNumber,
    feeAssignments,
    createdBy,
    autoGenerated: true,
    isDeleted: false
  });

console.log("PROFILE CREATED");
console.log(profile);


    return profile;

  } catch (error) {

  console.error(
    "FEE ASSIGNMENT ERROR:"
  );

  console.error(error);

  console.error(error.message);

  if (error.errors) {
    console.error(error.errors);
  }

  throw error;
}
};



// ======================
// ASSIGN FEES TO CLASS
// ======================

const assignFeesToClass =
async ({

  schoolId,

  academicYear,

  className,

  section = "ALL",

  createdBy

}) => {

  try {

    // ======================
    // FILTER
    // ======================

    const filter = {
  schoolId,
  currentClassName: className,
  studentStatus: "ACTIVE",
  isDeleted: false
};



    // ======================
    // SECTION FILTER
    // ======================

    if (

      section &&

      section !== "ALL"

    ) {

      filter.currentSection =
        section;
    }



    // ======================
    // STUDENTS
    // ======================
console.log(
  "FILTER =",
  filter
);
console.log("ASSIGN CLASS START");
console.log("CLASS =", className);
console.log("ACADEMIC YEAR =", academicYear);
console.log("FILTER =", filter);

const students = await Student.find(filter);

console.log("STUDENTS FOUND =", students.length);

students.forEach((s) => {
  console.log(
    s.name,
    s.currentClassName,
    s.studentStatus
  );
});


    // ======================
    // NO STUDENTS
    // ======================

    if (
      students.length === 0
    ) {

      return {

        success: false,

        message:
          "No students found"
      };
    }



    // ======================
    // LOOP
    // ======================

    const assignedStudents =
      [];



    for (

      const student
      of students

    ) {

      try {

        const profile =

          await assignFeesToStudent({

            schoolId,

            academicYear,

            student,

            createdBy
          });




        assignedStudents.push({

          studentId:
            student._id,

          name:
            student.fullName ||

            student.name,

          profileId:
            profile._id
        });

      } catch (error) {

        console.error(

          `FAILED FOR STUDENT ${student._id}`,

          error.message
        );
      }
    }



    return {

      success: true,



      totalStudents:
        students.length,



      assignedCount:
        assignedStudents.length,



      assignedStudents
    };

  } catch (error) {

    console.error(

      "CLASS ASSIGNMENT ERROR:",

      error
    );

    throw error;
  }
};



// ======================
// REASSIGN SINGLE STUDENT
// ======================

const reassignStudentFees =
async ({

  schoolId,

  academicYear,

  studentId,

  createdBy

}) => {

  try {

    const student =
      await Student.findOne({

        _id: studentId,

        schoolId
      });




    if (!student) {

      throw new Error(
        "Student not found"
      );
    }



    // DELETE OLD PROFILE
    await StudentFeeProfile.deleteMany({

      schoolId,

      academicYear,

      studentId
    });

console.log(
  "CREATING PROFILE FOR:",
  student.name
);
console.log("CREATING PROFILE");


    // REASSIGN
    const profile =

      await assignFeesToStudent({

        schoolId,

        academicYear,

        student,

        createdBy
      });




    return {

      success: true,

      profile
    };

  } catch (error) {

    console.error(

      "REASSIGN ERROR:",

      error
    );

    throw error;
  }
};



// ======================
// EXPORTS
// ======================

module.exports = {

  assignFeesToStudent,

  assignFeesToClass,

  reassignStudentFees
};